### ISSUE TITLE
Specify format of CelebA-HQ

### ISSUE THREAD

**Issue by Skylion007** [akanimax/MSG-GAN#1]
I was going to try to use some GPUs to get results for CelebA-HQ dataset in it's numpy format doesn't seem to work with this repo. What format do you expect CelebA-HQ to be in?

**Comment by akanimax** [comment]
Hi @Skylion007, my code currently only supports image files (.jpeg, .png, etc.). Can you provide link to your CelebA-HQ dataset in numpy format? I'll integrate it here. If you don't mind, can you share it on google drive (public)? It will be useful for others too.

Cheers!

**Comment by Skylion007** [comment]
Sure, https://github.com/nperraud/download-celebA-HQ . It's pretty common variant of the dataset along with the tfrecord, and hd5 formats.

**Comment by akanimax** [comment]
Hi! This has been fixed in commit [34f36aa433e0c34ba0b0bc636eaedb26f28e40bb](https://github.com/akanimax/MSG-GAN/commit/34f36aa433e0c34ba0b0bc636eaedb26f28e40bb#diff-b4b2e741bf17a12271001549cf37400b). Just point your directory containing the CelebAHQ `.npy` files to the `--img_dir` command-line argument and it should work.

Cheers :beers:!
