### ISSUE TITLE
CUDA OOM During Training Due to self.create_grid(). 

### ISSUE THREAD

**Issue by Skylion007** [akanimax/MSG-GAN#2]
For whatever reason, self.create_grid(self.gen(fixed_input), gen_img_files) seems to use a massive amount of GPU memory when training, so much so that I cannot train on 4TitanX with 1 image per GPU. There is probably some substantial optimization that can be done here to reduce the memory overhead. After removing it, I went from having out of memory errors to have 7GB freed on each GPU.

**Comment by akanimax** [comment]
Hi @Skylion007, Thanks for pointing that out.
Here is the full code of the `create_grid` method.

    @staticmethod
    def create_grid(samples, img_files):
        """
        utility function to create a grid of GAN samples
        :param samples: generated samples for storing list[Tensors]
        :param img_files: list of names of files to write
        :return: None (saves multiple files)
        """
        from torchvision.utils import save_image
        from numpy import sqrt

        samples = list(map(lambda x: th.clamp((x.detach() / 2) + 0.5, min=0, max=1),
                          samples))

        # save the images:
        for sample, img_file in zip(samples, img_files):
            save_image(sample, img_file, nrow=int(sqrt(sample.shape[0])))

I'll evaluate the memory consumption and find the leak. I believe this could be because of the `list(map())` chaining which is causing all the tensors to come into memry at once. 

For now, You can try to reduce the `--num_samples` argument in the `train.py` script to adjust to a configuration which fits in your GPU memory and avoids the OOM error. Removing the `create_grid` from the training code will stop the feedback samples from generating, which might hamper your ability of monitoring the training.
Thanks again! I'll work on it!

Cheers!

**Comment by akanimax** [comment]
Thanks for the issue and the fix :+1: 

Cheers :beers:!
